# Generated by Django 5.2.6 on 2025-10-01 23:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0004_alter_consulta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='edad_recomendada',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Edad recomendada'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='titulo',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='cantidad',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Aplicacion2.pedido', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='progreso',
            name='puntaje',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Puntaje'),
        ),
        migrations.AddConstraint(
            model_name='pedidodetalle',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_producto_por_pedido'),
        ),
        migrations.AddConstraint(
            model_name='progreso',
            constraint=models.UniqueConstraint(fields=('perfil', 'juego'), name='unique_progreso_perfil_juego'),
        ),
    ]
