# Generated by Django 5.2.6 on 2025-10-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0006_categoria_slug_juego_archivo_html_juego_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
