# Generated by Django 5.2.6 on 2025-10-06 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0008_alter_juego_creado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='juego',
            name='archivo_html',
            field=models.CharField(help_text='Ruta dentro de static/, ej: juegos/juego de formas/index.html', max_length=200, verbose_name='Archivo HTML'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='juego',
            name='edad_recomendada',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(18)], verbose_name='Edad recomendada'),
        ),
    ]
