# Generated by Django 5.2.6 on 2025-10-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion2', '0010_juego_categoria_alter_juego_archivo_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, unique=True, verbose_name='Slug'),
        ),
    ]
