services:
  - type: web
    name: tablemico
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt; python manage.py collectstatic --noinput
    startCommand: gunicorn Tablemico1.wsgi:application --log-file -
    envVars:
      - key: DJANGO_DEBUG
        value: 'False'
      - key: DJANGO_ALLOWED_HOSTS
        value: tablemico.onrender.com
      - key: DJANGO_SECRET_KEY
        generateValue: true
      # Optional: Use a managed Postgres DB and set DATABASE_URL automatically
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: tablemico-db
      #     property: connectionString
    # Optional database provisioning
    # databases:
    #   - name: tablemico-db
    #     plan: free
